### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by kruecab** [starsprung/amazon-ynab-sync#13]
Hi there -

Thanks for this tool, it is exactly what I need! I've not been able to get it to work successfully yet. I'm getting emails from Amazon about "order history report is ready", seems like I get two of those per run of the tool, so I know it's authenticating to Amazon and getting the report. However, this is the output from the tool:
```
$ amazon-ynab-sync --trace-warnings
{"level":"info","message":"Retrieving reports from Amazon","metadata":{},"timestamp":"2021-01-05T20:00:38.759Z"}
(node:13423) UnhandledPromiseRejectionWarning: Error: Invalid Record Length: columns length is 18, got 1 on line 2
    at Parser.__onRow (/snapshot/amazon-ynab-sync/node_modules/csv-parse/lib/index.js:762:9)
    at Parser.__parse (/snapshot/amazon-ynab-sync/node_modules/csv-parse/lib/index.js:635:40)
    at Parser._flush (/snapshot/amazon-ynab-sync/node_modules/csv-parse/lib/index.js:453:22)
    at Parser.prefinish (_stream_transform.js:142:10)
    at Parser.emit (events.js:315:20)
    at prefinish (_stream_writable.js:618:14)
    at finishMaybe (_stream_writable.js:626:5)
    at Parser.Writable.end (_stream_writable.js:570:5)
    at ReadStream.onend (_stream_readable.js:677:10)
    at Object.onceWrapper (events.js:421:28)
(Use `amazon-ynab-sync --trace-warnings ...` to show where the warning was created)
(node:13423) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13423) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any tips?

**Comment by starsprung** [comment]
Would you be willing to share the outputs of your reports with me (removing any sensitive data as necessary)? The tools uses Items, Orders and shipments and Refunds reports, so ideally I'd need to see all three. You can access them at https://www.amazon.com/gp/b2b/reports/. You can email them to s@starsprung.com.

**Comment by kruecab** [comment]
Thanks! As mentioned in my email, the Orders and Shipments report was not generated but the Items and Refunds reports were.

**Comment by starsprung** [comment]
Ok, looks like a relatively simple fix. I just need to handle the case where the report has no data.

**Comment by kruecab** [comment]
Cool. I’ll be happy to test a patch on my account if that helps.

**Comment by starsprung** [comment]
Fixed in underlying library, updated in this repo.

https://github.com/starsprung/amazon-order-reports-api/issues/15
https://github.com/starsprung/amazon-order-reports-api/pull/16
