### ISSUE TITLE
Gift Wrap is not accounted for

### ISSUE THREAD

**Issue by joeunrue** [starsprung/amazon-ynab-sync#20]
I ran the sync for the last 30 days and it got some of my Christmas gifts in the mix but the gift wrap was not added in anywhere. I had to go back and add separate line items to make my accounts reconcile. 

I don't know if this is possible to add given that it does not show up in the order export from amazon, but it would be a great to have before next Christmas!

**Comment by starsprung** [comment]
If it's not in the reports it may be a little tricky. I don't have any orders with gift wrapping on my account, would you be able to share any excerpts from your reports so I can take a look? You can send them privately to s@starsprung.com if you're willing (feel free to redact any sensitive information). The Orders and Shipments reports would likely be the one I'd need.

**Comment by joeunrue** [comment]
I just went ahead and redacted what needed redacted and attached my Christmas Shopping list. I don't see anything that would indicate gift wrap was purchased, as it was on items 2-4, the toy car, the socks, and Animal Crossing.

[01-Dec-2020_to_01-Jan-2021.zip](https://github.com/starsprung/amazon-ynab-sync/files/5783746/01-Dec-2020_to_01-Jan-2021.zip)

**Comment by starsprung** [comment]
Thanks! Would it be possible to see the "Orders and shipments" report type for the same time period too? I suspect even if there's no specific mention of a wrapping charge, the wrapping would at least be reflected in the order total and could be reflected as a "miscellaneous adjustment" in YNAB if there is any difference between that number and sum of the items + promotions + shipping.

**Comment by joeunrue** [comment]
Sorry, my mistake. Here is the orders and shipments form.

There doesn't seem to be a specific column for gift wrap, but the Total Charged column is correct
[08-Dec-2020_to_07-Jan-2021.zip](https://github.com/starsprung/amazon-ynab-sync/files/5783912/08-Dec-2020_to_07-Jan-2021.zip)

It looks like the Gift Wrap is included in the Total Charged amount and can be approximated by subtracting the other columns from the Total Charged column, though it is a per-shipment amount and not a per-item amount. Still that would be more helpful than nothing

**Comment by starsprung** [comment]
Right, it's harder to get the per-item values correct, but the account total would at least reconcile without adding entries manually. I do plan to look into the possibility of adding an option to attribute discounts and shipping to individual items proportionally (https://github.com/starsprung/amazon-ynab-sync/issues/18) and this would be a another charge that could also be handled that way. There's no 100% accurate way to do it though, so that options would come with the caveat that it's only an estimate.
